### ISSUE TITLE
Facebook SDK conflicts

### ISSUE THREAD

**Issue by jayspringfield** [brightcove-archive/ooyala_native-skin#447]
The OoyalaSkinSDK.jar file contains classes of the form:

com/facebook/internal/BundleJSONConverter.class

but these classes create conflicts when including the standard facebook SDK into a project via `compile('com.facebook.android:facebook-android-sdk:4.+')`

Is there a reason the jar contains classes with the internal facebook namespace?  Is it not possible to have both the native-skin and standard facebook functionality in the same project?

**Comment by lental** [comment]
Good catch, we used some Facebook code but didn't move it out of their namespace.  I fixed it here:  https://github.com/ooyala/native-skin/pull/448

We will make sure that gets into the next release.  If you want to be unblocked now, you can try:
1. checking out the native-skin repo, stable branch
2. cherry-picking the commit onto stable
3. importing the ooyalaSkinSDK module into your applicaton/settings.gradle, for example:
include ':ooyalaSkinSDK'
project(':ooyalaSkinSDK').projectDir=new File(settingsDir, '../../native-skin/sdk/android/ooyalaSkinSDK/')
4. compiling that module into your application instead of the OoyalaSDK.jar and OoyalaSkinSDK.jar
5. Running the app

You should not see that issue anymore.

**Comment by lental** [comment]
This should be fixed in 4.14.0 of Ooyala Skin. Please reopen if you still see the issue.

Thanks!
Mike
